# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78fecbcbcb778c40dba63b019d09787de24c0e9a1a7f0df222cfe688ef38281e96bae57b19664d9cb0a88eb9a261e9f6aec530ededa88ddef3c48b4bbb025f82

test:
  secret_key_base: c96305c397b9aaf34b55d0ea42702fb91758ed3d3814834ebf1a072516858251aac6e75d4f32ea0c5c7d6b32dc6509984f54121a50879d8bac2c52fc4f1893d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
